[project]
name = "wiki"
version = "0.7.6"
description = "A wiki built on HIVE"
dependencies = [
    "flask",
    "flask_session",
    "beem",
    "redis",
    "bleach",
    "psycopg2-binary",
    "diff-match-patch"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
